### Gradle properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true

### Mod Gradle properties
net.minecraftforge.gradle.merge-source-sets=true
fabric.loom.disableObfuscation=true
multiloader.enableAdvancedVersionSearch=true
multiloader.editPublishVersions=true

### Mod properties
mod.name=Simple Datapacks
mod.id=simple_datapacks
mod.version=2.8.2
mod.description=Simplifying the use of datapacks

### Publishing
mod.modrinth=Re6xQ62Z
mod.curseforge=1325828
mod.github=simple-datapacks
