# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Extra dependencies see: https://linkie.shedaniel.dev/dependencies

["1.19.4"]
pub-end="1.20.1"

["1.20.2"]
pub-end="1.20.4"

["1.21.1"]
pub-start="1.20.5"
pub-end="1.21.1"

["1.21.1-forge"]
pub-start="1.20.6"

["1.21.1-neoforge"]
pub-start="1.21"

["1.21.3"]
pub-start="1.21.2"
pub-end="1.21.11"

["26.1.1"]
pub-start="26.1"
pub-end="latest"
