# Fabric versions see: https://fabricmc.net/develop
# Forge versions see: https://files.minecraftforge.net
# NeoForge versions see: https://neoforged.net
# Extra dependencies see: https://linkie.shedaniel.dev/dependencies

["1.16.5"]
pub-end="1.18.2"

["1.16.5-forge"]
pub-end="1.16.5"

["1.18"]
pub-end="1.18.2"

["1.19"]
pub-end="1.19.2"

["1.19.4"]
pub-start="1.19.3"
pub-end="1.20.1"

["1.20.2"]
pub-end="1.20.4"

["1.20.2-fabric"]
pub-end="1.21.1"

["1.21.1"]
pub-start="1.20.5"

["1.21.1-forge"]
pub-start="1.20.6"

["1.21.1-neoforge"]
pub-start="1.21"

["1.21.3"]
pub-end="1.21.11"

["26.1.2"]
pub-end="latest"
